version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - DATABASE_URL=file:/data/prod.db
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-y0uR_SuP3r_S3cr3t_N3xt4uth_K3y}
      - UPLOAD_DIR=/data/uploads
      - NODE_ENV=production
    ports:
      - '3000:3000'
    volumes:
      - pontocerto_data:/data

volumes:
  pontocerto_data:

